### ISSUE TITLE
print issue

### ISSUE THREAD

**Issue by nikols** [barsi/odoo-rtl#10]
hello my friend,
please help to resolve this issue, i try to check on few servers based on windows server 2008r2 and few on windows 7 but always have the same issue, and i try to download and install another version of odoo from 2014.11 to 2015.02.16 but still have same issue. 
thank you

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20141226\server\openerp\addons\report\controllers\main.py", line 121, in report_download
  File "C:\Program Files (x86)\Odoo 8.0-20141226\server\.\openerp\http.py", line 388, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20141226\server\openerp\addons\report\controllers\main.py", line 65, in report_routes
  File "C:\Program Files (x86)\Odoo 8.0-20141226\server\.\openerp\api.py", line 237, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20141226\server\openerp\addons\report\models\report.py", line 269, in get_pdf
  File "C:\Program Files (x86)\Odoo 8.0-20141226\server\.\openerp\api.py", line 237, in wrapper
  File "C:\Users\Administrator\AppData\Local\OpenERP S.A.\Odoo\addons\8.0\report_rtl\models\report.py", line 157, in _run_wkhtmltopdf
  File "subprocess.pyc", line 709, in __init__
  File "subprocess.pyc", line 957, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified

**Comment by majeedid** [comment]
This issue is still not resolved even after upgrading the wkhtmltopdf to latest version!
If any one have a solution please just update us

**Comment by majeedid** [comment]
Any body has this issue resolved to him yet?
