### ISSUE TITLE
report-RTL not work

### ISSUE THREAD

**Issue by Ayhamhafez** [barsi/odoo-rtl#14]
I installed the latest odoo v8 from the github.com/odoo/odoo and every thing is OK, after using the report-rtl every single report in Arabic not printed and give errors such this error below

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/report/controllers/main.py", line 125, in report_download
    response = self.report_routes(reportname, converter='pdf', *_dict(data))
  File "/opt/odoo/odoo-server/openerp/http.py", line 402, in response_wrap
    def response_wrap(_args, *_kw):
  File "/opt/odoo/odoo-server/addons/report/controllers/main.py", line 65, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/report/models/report.py", line 191, in get_pdf
    html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/report/models/report.py", line 166, in get_html
    return particularreport_obj.render_html(cr, uid, ids, data=data, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/report/models/abstract_report.py", line 66, in render_html
    return self.pool['report'].render(cr, uid, [], self._template, docargs, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/website_report/report.py", line 47, in render
    return super(Report, self).render(cr, uid, ids, template, values=values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/report_rtl/models/report.py", line 84, in render
    return view_obj.render(cr, uid, template, values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 172, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 1029, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/web_rtl/models/ir_qweb.py", line 42, in render
    context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 261, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 298, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 436, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 298, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 422, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 298, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 445, in render_tag_call
    return self.render(cr, uid, template, d)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/web_rtl/models/ir_qweb.py", line 42, in render
    context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 261, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 298, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 373, in render_tag_esc
    inner = widget.format(template_attributes['esc'], options, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 992, in format
    return escape(self._format(inner, options, qwebcontext))
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 989, in _format
    return self.pool['ir.qweb'].eval_str(inner, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 213, in eval_str
    val = self.eval(expr, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 205, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 202, in eval
    return qwebcontext.safe_eval(expr)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 88, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/opt/odoo/odoo-server/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
QWebException: "'NoneType' object is not callable" while evaluating
"context_timestamp(datetime.datetime.now()).strftime('%Y-%m-%d %H:%M')"

**Comment by majeedid** [comment]
Yes, this happened to me also.
I think this is a major issue which necessarily should be solved As soon as possible
